export const APPLICATIONS_INIT   = 'APPLICATIONS_INIT'
export const APPLICATIONS_DEINIT = 'APPLICATIONS_DEINIT'
export const APPLICATIONS_UPDATE = 'APPLICATIONS_UPDATE'
 export const APPLICATIONS_NEXT  = 'APPLICATIONS_NEXT'