export const FORM_NEW_CATEGORIE_FAIL  = 'FORM_NEW_CATEGORIE_FAIL'
export const FORM_NEW_CATEGORIE_INIT   = 'FORM_NEW_CATEGORIE_INIT'
export const FORM_NEW_CATEGORIE_DEINIT = 'FORM_NEW_CATEGORIE_DEINIT'