export const LIST_ARTICLES_INIT  = 'LIST_ARTICLES_INIT'
export const LIST_ARTICLES_NEXT  = 'LIST_ARTICLES_NEXT'
export const LIST_ARTICLES_SORT  = 'LIST_ARTICLES_SORT'
export const LIST_ARTICLES_CNANGE  = 'LIST_ARTICLES_CNANGE'
